### PR TITLE
Midi improvements, voice allocation reorder, ghost note fix

### LINKED ISSUE #39: Latch should be disabled during step record
Step record depends on fingers being released from the plate, which triggers automatically moving to the next step. If latch is holding notes, this automatic move is never triggered. It also feels clunky overall - you'd probably not want to engage latch while step-recording anyway

### PR DESCRIPTION
**Pull request by RJ-Eckie**
I decided to put these all in one PR. I did put everything in separate commits. If there's no bugs, this should constitute v0.B

### Improve midi voice allocation
1. Incoming midi notes try to map themselves to a string they could also be played on by touch
  a. The average pitch of each string `(pad 0 pitch + pad 7 pitch) / 2` is collected and compared to the midi pitch. We try to map the midi note to the (non-sounding) string with the closest average pitch
  b. Even if the first desired string is not available, mapping to one string higher or lower still yields a fair chance that the midi note exists on this string
  c. If there is no non-sounding string available, we map to the (non-pressed) string with the lowest volume
2. Before returning the chosen string number, the position of the midi note on the string is defined
  a. Notes in the scale map to the exact pad on the string that represents the midi pitch
  b. Accidentals round down to the nearest note in scale
  c. Notes fully higher or lower than the chosen string map to pad 7 and 0 respectively
3. If there is no non-pressed string available, the midi note is ignored

_From this point, sequencing or latching midi notes does not seem far away_
### Reorder touch-source priority
Priority is now:
1. Touch
2. Sequencer
3. Midi

Higher priority notes will sound instead of lower priority notes when played on the same string at the same time. But when the higher priority note releases and the lower priority note is still pressed, the lower priority note will take over again.
### CV gate scaling
CV gate scaling of the pressure on a string is now applied at the very end of the note registration. Touch, sequencer and midi are all processed first, and whatever pressure is generated at the end gets scaled by the incoming cv gate signal
### Ghost note fix
Whenever touch, latch or sequencer generates a note, its touch position is stored in memory. When no touch is generated at all, `DoAudio()` always plays from the position stored in memory. This prevents pitches from skipping after a touch is released or cancelled.
### Latch during step record mode
- Being in latch mode could complicate step recording. For that reason, latch will now be temporarily suppressed when a new latch is started while in step record mode. This brings back the expected auto-step functionality in step record mode. After step record is turned off, latch resumes working as usual (fixes #39)
- If a latch is playing when step record mode is turned on, it will be recorded into the active step. The sequencer behavior in this scenario is a bit wonky. The alternative is stopping the latch immediately as soon as record is enabled, which could lead to undesired situations if record is pressed accidentally. I feel like the current solution is the least-bad one

### CODE REVIEW

File: sw/Core/Src/touch.h [hunk 1]
```diff
@@ -551,33 +553,62 @@ u8 find_midi_note(u8 chan, u8 note) {
...
-	// 	}
-	// 	if (attempt >=8 || midi_channels[ch] == 255)
-	// 		return ch;
-	// }
-	// // give up
-	// return (midi_next_finger++) & 7;
+	// Reverse-engineering the central pitch of a string from the calculations in DoAudio() is a little too 
+	// complex for me to figure out. Is there a simpler way to get those? For now I'm implemeting a very
+	// simple way of mapping midi notes over the strings from low to high.
+
```
Comment (mmalex) [inline sw/Core/Src/touch.h:566]: i agree its super gnarly. my suggestion to avoid a big refactor would actually be for the DoAudio() routine to maintain a 'lowest note' and 'highest note' in each string, or even just a midpoint, and then have this code swoop in and compare to that?

**Comment by RJ-Eckie** [comment]
Implemened midi-persistence
Improved midi-to-string mapping: couldn't find tools to reliably convert pitch to pad value, but I did find the tools to convert midi note number to pitch and to convert string and pad numbers to pitch. Using this, I check the midi pitch against the string and pad pitch values to find the string and pad a midi note should fall on, see updated PR notes

**Comment by RJ-Eckie** [comment]
Improved midi pressure scaling needs a global parameter, so I've taken it out for now.
I think this should be about ready

**Review by mmalex — APPROVED** [review]
lets go! if something gets messed up we can always iterate. lets go to main!
